version: '3'
services:
  redis:
    image: redis
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  webservice:
    build: ./user-api
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  redis-data: