apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: galiaydaraliev/nodejs:latest  #image
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: redis-service
          - name: REDIS_PORT
            value: "6379"
